### PR TITLE
Adds relative-datetime-padded required for BETWEEN SQL optimizations

### PR DESCRIPTION
**Pull request by nikita2206**
Required for https://github.com/metabase/metabase/pull/9860

### CODE REVIEW

**Review by camsaul — CHANGES_REQUESTED** [review]
Hi @nikita2206 

Thanks for this PR.

I'd rather add options to the `relative-datetime` clause instead of adding an entire new clause. We have enough different clauses already :)

Something like

```clj
[:relative-datetime -1 :day]                  ; without options. Default is padded = false
[:relative-datetime -1 :day {:padded? true}]` ; with options
```
The string filter options are an example where we're support an optional options argument. https://github.com/metabase/mbql/blob/master/src/metabase/mbql/schema.clj#L380

**Comment by camsaul** [comment]
Also, why is this required at all for `BETWEEN` optimizations? Is there a corresponding PR for https://github.com/metabase/metabase?

**Comment by nikita2206** [comment]
@camsaul I'll change this to use parameters then

The other PR is here: https://github.com/metabase/metabase/pull/9860   
I was asking there your opinion but I guess notifications got lost in the inbox, is there any other way I could ping you guys when I update these PRs?

**Comment by nikita2206** [comment]
@camsaul does this make sense for a `relative-datetime` with options?

```
(def ^:private DatetimeOptions
  {(s/optional-key :padded?) s/Bool}) ; default false

(defclause relative-datetime
  n    (s/cond-pre (s/eq :current) s/Int)
  optionsOrUnit (optional (s/cond-pre RelativeDatetimeUnit DatetimeOptions))
  options (optional DatetimeOptions))
```

Ideally what we want to express here (in haskell's syntax) is: 
```
data RelativeDatetime = Now RelativeDatetimeOptions | Relative Int Unit RelativeDatetimeOptions
```
But I don't think it's possible to do this here. What we could do is:
```
(def ^:private DatetimeOptions
  {(s/optional-key :padded?) s/Bool}) ; default false

(def ^:private RelativeDatetime
  n    (s/cond-pre (s/eq :current) s/Int)
  unit (optional RelativeDatetimeUnit))

(defclause relative-datetime
  relative RelativeDatetime
  options (optional DatetimeOptions))
```
But this will amount to e.g. `[:relative-datetime [-1 :day] {:padded? false}]` and `[:relative-datetime [:current] {:padded? false}]` and `[:relative-datetime [-1 :day]]` instead of current `[:relative-datetime :current]` or `[:relative-datetime -1 :day]` which may be undesired.

**Comment by camsaul** [comment]
```clj
(defclause relative-datetime
  n    (s/cond-pre (s/eq :current) s/Int)
  optionsOrUnit (optional (s/cond-pre RelativeDatetimeUnit DatetimeOptions))
  options (optional DatetimeOptions))
```

looks like what we'd want. Not sure if it's possible to generate the right kind of schema with our `defclause` macro however so you might have to do it by hand. I tried this and it seems to work:

```clj
(def RelativeDatetimeOptions
  {(s/optional-key :padded?) s/Bool})

(def relative-datetime
  "Schema for a `relative-datetime` clause."
  (s/conditional
   (every-pred sequential? #(= (second %) :current))
   [(s/one (s/eq :relative-datetime) "clause name")
    (s/one (s/eq :current) "current")
    (s/optional RelativeDatetimeOptions "options")]

   :else
   [(s/one (s/eq :relative-datetime) "clause name")
    (s/one s/Int "n")
    (s/one RelativeDatetimeUnit "unit")
    (s/optional RelativeDatetimeOptions "options")]))
```

Tested it as follows and it looks like it's working:

```clj
(defn- check []
  (doseq [clause [[:relative-datetime :current]
                  [:relative-datetime :current {}]
                  [:relative-datetime :current {:padded? true}]
                  [:relative-datetime -1 :day]
                  [:relative-datetime -1 :day {}]
                  [:relative-datetime -1 :day {:padded? false}]
                  ;; invalid
                  [:relative-datetime :current :day]
                  [:relative-datetime :current :day {}]
                  [:relative-datetime -1 {}]
                  [:relative-datetime -1 {} {}]]]
    (printf "%-45s valid? %s\n" clause ((complement s/check) relative-datetime clause))))

;; [:relative-datetime :current]                 valid? true
;; [:relative-datetime :current {}]              valid? true
;; [:relative-datetime :current {:padded? true}] valid? true
;; [:relative-datetime -1 :day]                  valid? true
;; [:relative-datetime -1 :day {}]               valid? true
;; [:relative-datetime -1 :day {:padded? false}] valid? true
;; [:relative-datetime :current :day]            valid? false
;; [:relative-datetime :current :day {}]         valid? false
;; [:relative-datetime -1 {}]                    valid? false
;; [:relative-datetime -1 {} {}]                 valid? false

```

**Comment by camsaul** [comment]
@nikita2206 sorry for not looking at your other PR in Metabase. I get dozens of GitHub notifications a day for MB-related stuff so sometimes I end up missing stuff. 

Let me know once you get a change to make the changes requested here and I'll take a look at the Metabase PR and see if it all makes sense together

**Comment by nikita2206** [comment]
Hey @camsaul please have a look at this when you're free. I wasn't able to test this with metabase yet as I couldn't get jitpack to build mbql for some reaason (it builds on my local though)

**Comment by nikita2206** [comment]
Will reopen new PR

**Pull request closed without merging**
